--TRIGGER (GATILHO)
--SÃO GATILHOS QUE SÃO ACIONADOS ANTES OU DEPOIS DE UM
--INSERT/DELETE/UPDATE
--SEGUE CÓDIGO DE EXEMPLO

--CRIANDO UMA TABELA EM QUE QUEREMOS QUE SEJA ATUALIZADA
--SEMPRE QUE UMA NOTA FISCAL FOR CRIADA
CREATE TABLE TAB_FATURAMENTO
(DATA_VENDA DATE NULL, TOTAL_VENDA FLOAT);

--APAGANDO CASO HAJA ALGUMA PARA TERMOS UM EXEMPLO LIMPO
DELETE FROM ITEMS_NOTAS;
DELETE FROM NOTAS;

--OLHANDO OS DADOS PARA SABER DE QUAL VOU FAZER A INCLUSÃO
SELECT * FROM CLIENTES;
SELECT * FROM VENDEDORES;
SELECT * FROM PRODUTOS;

--COMO SERIA O PROCESSO MANUALMENTE:

--INSERIMOS EM NOTAS
INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES
('0100', TO_DATE('2019-06-05','YYYY-MM-DD'), '1471156710', '235', 0.10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0100', '1040107', 1000, 10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0100', '1000889', 1000, 10);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES
('0101', TO_DATE('2019-06-05','YYYY-MM-DD'), '3623344710', '235', 0.10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0101', '1040107', 1000, 10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0101', '1000889', 1000, 10);

--OLHANDO OS DADOS INSERIDOS
SELECT * FROM NOTAS;
SELECT * FROM ITEMS_NOTAS;

--OLHANDO O RELATÓRIO QUE DESEJAMOS
--AGRUPADO POR DATA OLHAMOS O TOTAL DE VENDA
SELECT NOTAS.DATA_VENDA, SUM(ITEMS_NOTAS.QUANTIDADE * ITEMS_NOTAS.PRECO) AS TOTAL_VENDA
FROM NOTAS INNER JOIN ITEMS_NOTAS
ON NOTAS.NUMERO = ITEMS_NOTAS.NUMERO
GROUP BY NOTAS.DATA_VENDA;

--ENTÃO ADICIONAMOS ESSE SELECT
INSERT INTO TAB_FATURAMENTO
SELECT NOTAS.DATA_VENDA, SUM(ITEMS_NOTAS.QUANTIDADE * ITEMS_NOTAS.PRECO) AS TOTAL_VENDA
FROM NOTAS INNER JOIN ITEMS_NOTAS
ON NOTAS.NUMERO = ITEMS_NOTAS.NUMERO
GROUP BY NOTAS.DATA_VENDA;

--OLHANDO OS DADOS GRAVADOS NA TABELA
SELECT * FROM TAB_FATURAMENTO;

--ESTE FOI O PROCESSO MANUAL PORÉM NÃO É MUITO USUAL
--IMAGINE QUE EU VÁ INSERIR OUTRA NOTA AGORA PARA ATUALIZAR 
--NOSSA TABELA DO RELATÓRIO PARA FAZER ISSO EU TEREI QUE APAGAR OQ JÁ EXISTE
--E FAZER NOVAMENTE O INSERT, VAI FICAR BEM REPETITIVO

--PROCESSO MANUAL CASO EU ADICIONASSE MAIS UMA NOTA:

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES
('0102', TO_DATE('2019-06-05','YYYY-MM-DD'), '3623344710', '235', 0.10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0102', '1040107', 1000, 10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0102', '1000889', 1000, 10);

DELETE FROM TAB_FATURAMENTO;

INSERT INTO TAB_FATURAMENTO
SELECT NOTAS.DATA_VENDA, SUM(ITEMS_NOTAS.QUANTIDADE * ITEMS_NOTAS.PRECO) AS TOTAL_VENDA
FROM NOTAS INNER JOIN ITEMS_NOTAS
ON NOTAS.NUMERO = ITEMS_NOTAS.NUMERO
GROUP BY NOTAS.DATA_VENDA;

--PORTANTO PODEMOS CRIAR UMA ***TRIGGER***
--CRIA UMA TRIGGER NOME - ESSA TRIGGER ACONTECE ANTES/DEPOIS/INVÉS DE 
--                                              BEFORE/AFTER/INSTEAD OF
--NA TABELA TAL - BEGIN...END (ENTRE ELES OQUE A TRIGGER FAZ)
CREATE TRIGGER TG_CALCULO_FATURAMENTO
AFTER INSERT ON ITEMS_NOTAS
BEGIN
DELETE FROM TAB_FATURAMENTO;
INSERT INTO TAB_FATURAMENTO
SELECT NOTAS.DATA_VENDA, SUM(ITEMS_NOTAS.QUANTIDADE * ITEMS_NOTAS.PRECO) AS TOTAL_VENDA
FROM NOTAS INNER JOIN ITEMS_NOTAS
ON NOTAS.NUMERO = ITEMS_NOTAS.NUMERO
GROUP BY NOTAS.DATA_VENDA;
END;

--A PARTIR DESSE MOMENTO QUALQUER INSERT QUE EU DER NA TABELA SELECIONADA
--ELE JÁ VAI ATUALLIZAR O RELATÓRIO

--TESTANDO:
--INSERÇÃO
INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES
('0103', TO_DATE('2019-06-05','YYYY-MM-DD'), '3623344710', '235', 0.10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0103', '1040107', 1000, 10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0103', '1000889', 1000, 10);

INSERT INTO NOTAS (NUMERO, DATA_VENDA, CPF, MATRICULA, IMPOSTO)
VALUES
('0104', TO_DATE('2019-06-06','YYYY-MM-DD'), '3623344710', '235', 0.10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0104', '1040107', 1000, 10);
INSERT INTO ITEMS_NOTAS (NUMERO, CODIGO, QUANTIDADE, PRECO)
VALUES
('0104', '1000889', 1000, 10);
--CONFERINDO QUE A TRIGGER SALVOU
SELECT * FROM TAB_FATURAMENTO;

COMMIT