--VAMOS ARRUMAR O TAMANHO DE UM CAMPO PARA QUE FIQUE IGUAL AS DUAS TABELAS

ALTER TABLE PRODUTOS MODIFY (EMBALAGEM VARCHAR(50));

--INSERINDO MULTIPLOS REGISTROS (VINDOS DE OUTRA TABELA)
INSERT INTO CLIENTES
SELECT CPF, NOME, ENDERECO_1 AS ENDERECO, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO AS DATA_NASCIMENTO,
IDADE, SEXO, LIMITE_DE_CREDITO AS LIMITE_CREDITO, VOLUME_DE_COMPRA AS VOLUME_COMPRA, PRIMEIRA_COMPRA
FROM TABELA_DE_CLIENTES WHERE CPF NOT IN (SELECT CPF FROM CLIENTES);
--USAMOS A SUBQUERY, OU SEJA, INSERE ESSE SELECT
--É IMPORTANTE QUE OS NOMES DO SELECT E DA TABELA
--QUE QUEREMOS IMPORTAR SEJAM OS MESMOS POR ISSO
--UTILIZAMOS O ALIAS (APELIDOS) NOS CAMPOS
--AINDA NO FINAL INCLUIMOS UMA CONDIÇÃO
--QUE ESTES CAMPOS SÓ SERAO INCLUIDOS SE 
--NÃO ESTIVEREM JÁ NA TABELA (PARA EVITAR ERRO POR CONTA
--DA PK)