--CONVERSÃO DE DADOS

--STRING PARA DATA
SELECT TO_DATE('12/11/2019', 'DD/MM/YYYY') FROM DUAL;

SELECT TO_DATE('12/11/2019', 'MM/DD/YYYY') FROM DUAL;

--DATA PARA CHAR
SELECT TO_CHAR(SYSDATE, 'MM/DD/YYYY HH12:MM:SS AM') FROM DUAL;

--PEGA (PARAMETRO (NO CASO MES)) DA DATA
SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019', 'DD/MM/YYYY')) FROM DUAL;

SELECT EXTRACT(MONTH FROM TO_DATE('12/11/2019', 'MM/DD/YYYY')) FROM DUAL;

--CARACTER PARA NUMBER
SELECT TO_NUMBER('10') + 100 FROM DUAL;

--10 VIRA 00010
SELECT TO_CHAR(10, '00000') FROM DUAL;

--PEGA DETERMINADO CAMPO (ONDE ESTÁ O 10) E SE FOR NULO COLOQUE ALGO
SELECT NVL(10,0) FROM DUAL;

--PEGA O MAIOR 
SELECT GREATEST(10,20,15) FROM DUAL;
