--FUNÇÕES MATEMÁTICAS

--ARREDONDA CONFORME AS REGRAS MATEMÁTICAS (A PARTIR DO .5 É PARA CIMA)
SELECT ROUND(3.4) FROM DUAL;
SELECT ROUND(3.6) FROM DUAL;

--ARREDONDA SEMPRE PARA BAIXO
SELECT TRUNC(3.4) FROM DUAL;
SELECT TRUNC(3.6) FROM DUAL;
SELECT FLOOR(3.4) FROM DUAL;
SELECT FLOOR(3.6) FROM DUAL;

--ARREDONDA SEMPRE PARA CIMA
SELECT CEIL(3.4) FROM DUAL;
SELECT CEIL(3.6) FROM DUAL;

--POENCIA -> X ELEVADO A Y
SELECT POWER(10,4) FROM DUAL;

--EXPONENCIAL ELEVADO A X
SELECT EXP(10) FROM DUAL;

--RAIZ QUADRADA DE 10
SELECT SQRT(144) FROM DUAL;

--RETORNA 1 SE FOR POSITIVO
-- -1 SE FOR NEGATIVO
--E 0 SE FOR 0
SELECT SIGN (10) FROM DUAL;

--RETORNA O VALOR ABSOLUTO OU SEJA
-- X => X OU -X => X
SELECT ABS(10000) FROM DUAL;

--RESTO DA DIVISÃO INTEIRA DE X POR Y
SELECT MOD(10, 6) FROM DUAL;