--O INNER JOIN PEGA SOMENTE OQ ESTÁ PRESENTE NAS DUAS TABELAS
SELECT * FROM TABELA_DE_VENDEDORES;

SELECT * FROM NOTAS_FISCAIS;

SELECT MATRICULA, NOME, COUNT(*) AS NUMERO_NOTAS FROM NOTAS_FISCAIS
GROUP BY MATRICULA, NOME;

--O ON SERVE PARA FALAR EM QUAL CAMPO ELES SE LIGAM
SELECT A.MATRICULA, B.NOME, COUNT(*) FROM NOTAS_FISCAIS A 
INNER JOIN TABELA_DE_VENDEDORES B
ON A.MATRICULA = B.MATRICULA
GROUP BY A.MATRICULA, B.NOME;

--LEFT E RIGHT JOIN
SELECT COUNT(*) FROM TABELA_DE_CLIENTES;

SELECT CPF, COUNT(*) FROM NOTAS_FISCAIS GROUP BY CPF;
--LEFT - PEGA TUDO QUE É DA ESQUERDA E DA DIREITA SOMENTE 
--OQ FAZ PARTE DA DIREITA
SELECT DISTINCT A.CPF AS CPF_DO_CADASTRO
, A.NOME, B.CPF AS CPF_DA_NOTA 
FROM TABELA_DE_CLIENTES A LEFT JOIN NOTAS_FISCAIS B
ON A.CPF = B.CPF
WHERE B.CPF IS NULL;

--PEGA TUDO QUE FAZ PARTE DA DIREITA E DA ESQUERDA 
--SOMENTE OQ PERTENCE A DIREITA
SELECT DISTINCT A.CPF AS CPF_DO_CADASTRO
, A.NOME, B.CPF AS CPF_DA_NOTA 
FROM NOTAS_FISCAIS B RIGHT JOIN TABELA_DE_CLIENTES A
ON A.CPF = B.CPF
WHERE B.CPF IS NULL;
--------------------------
--FULL JOIN PEGA A DIREITA E A ESQUERDA POREM SE NÃO OUVER 
--RELACIONAMENTO ELE MOSTRA UM NULL
SELECT TABELA_DE_VENDEDORES.NOME AS NOME_VENDEDOR
, TABELA_DE_VENDEDORES.BAIRRO AS BAIRRO_VENDEDOR
, TABELA_DE_CLIENTES.NOME AS NOME_CLIENTE
, TABELA_DE_CLIENTES.BAIRRO AS BAIRRO_CLIENTE
FROM TABELA_DE_VENDEDORES
FULL JOIN TABELA_DE_CLIENTES
ON TABELA_DE_VENDEDORES.BAIRRO = TABELA_DE_CLIENTES.BAIRRO;

--CROSS JOIN CRUZA TODOS COM TODOS
SELECT TABELA_DE_VENDEDORES.NOME AS NOME_VENDEDOR
, TABELA_DE_VENDEDORES.BAIRRO AS BAIRRO_VENDEDOR
, TABELA_DE_CLIENTES.NOME AS NOME_CLIENTE
, TABELA_DE_CLIENTES.BAIRRO AS BAIRRO_CLIENTE
FROM TABELA_DE_VENDEDORES,  TABELA_DE_CLIENTES;