--UNION FAZ CONFORME O NOME
--UNE DUAS CONSULTAS
--DEVEM TER AS MESMAS QNTD DE COLUNAS E ELAS DEVEM TER O MESMO TIPO
--O UNION "FAZ UM DISTINCT" E NÃO REPETE LINHAS QUE SEJAM IGUAIS ENTRE AS
--DUAS CONSULTAS
--O UNION ALL NÃO FAZ ISSO MOSTRANDO OS REPETIDOS

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO AS BAIRRO_CLIENTE FROM TABELA_DE_CLIENTES
UNION ALL
SELECT DISTINCT BAIRRO AS BAIRRO_VENDEDOR FROM TABELA_DE_VENDEDORES;

SELECT DISTINCT BAIRRO AS BAIRRO, 'CLIENTE' AS TIPO FROM TABELA_DE_CLIENTES
UNION
SELECT DISTINCT BAIRRO AS BAIRRO, 'VENDEDOR' AS TIPO FROM TABELA_DE_VENDEDORES;