--VIEWS SÃO UMA TABELA LÓGICA - ELAS SÃO CRIADAS A PARTIR
--DE UM COMANDO SQL
CREATE VIEW VW_EMBALAGENS AS 
SELECT EMBALAGEM, SUM(PRECO_DE_LISTA) AS SOMA_PRECO
FROM TABELA_DE_PRODUTOS GROUP BY EMBALAGEM;

SELECT * FROM VW_EMBALAGENS;

SELECT * FROM VW_EMBALAGENS WHERE SOMA_PRECO <= 80;

SELECT * FROM TABELA_DE_PRODUTOS A
INNER JOIN VW_EMBALAGENS B ON
A.EMBALAGEM = B.EMBALAGEM;