--PARAMETROS NOMEADOS

--PARA EXECUTARMOS O MÉTODO PASSAMOS OS PARAMETROS NA ORDEM
--QUE ELES FORAM DECLARADOS NA PROCEDURE
--MAS NEM SEMPRE SABEREMOS ISSO
--ENTÃO PODEMOS PEGAR O NOME_PARAMETRO=> VALOR_PARAMETRO
--E COM ISSO A ORDEM NÃO IMPORTA

--SEGUE EXEMPLO NA ORDEM
DECLARE
   v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%type := 2;
BEGIN
  FOR v_ID IN 1..6 LOOP 
      atualizar_cli_seg_mercado(p_ID => v_ID, p_SEGMERCADO_ID => v_SEGMERCADO_ID);
  END LOOP;
END;

--FORA DA ORDEM
DECLARE
   v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%type := 1;
BEGIN
  FOR v_ID IN 1..6 LOOP 
      atualizar_cli_seg_mercado(p_SEGMERCADO_ID => v_SEGMERCADO_ID, p_ID => v_ID);
  END LOOP;
END;