--CURSOR COM FOR


DECLARE
--DECLARAMOS DA MESMA FORMA PORÉM NÃO PRECISAMOS TER MAIS
--AS VARIAVEIS PARA CADA COLUNA
   CURSOR cur_CLIENTE IS SELECT ID FROM CLIENTE;
   --ESSA VARIAVEL N TEM NADA A VER COM O CURSOR, É UMA
   --VARIAVEL DE TRABALHO MESMO PARA UTILIZARMOS NA PROC
   v_SEGMERCADO_ID CLIENTE.SEGMERCADO_ID%type := 1;
BEGIN
--O FOR JÁ ABRE E FECHA SOZINHO O CURSOR E ESSA
--VARIAVEL CLI_REC É UM ARRAY DE CURSOR
--POR ISSO AO CHAMARMOS OQ QUEREMOS COLOCAMOS ALI
--cli_rec.ID
   FOR cli_rec IN cur_CLIENTE LOOP
       atualizar_cli_seg_mercado(p_SEGMERCADO_ID => v_SEGMERCADO_ID, p_ID => cli_rec.ID);
   END LOOP;
END;



