--PRIMEIRO PROGRAMA PL/SQL

--ESTE COMANDO É PQ VAMOS UTILIZAR UMA BIBLIOTECA DE SAÍDA
--ENTÃO DEVEMOS ATIVAR
SET SERVEROUTPUT ON;

/*
A ESTRUTURA BASICA É:
DECLARE
    DECLARAÇÃO DAS VARIAVEIS;
BEGIN
    CÓDIGO;
END;
*/
DECLARE
   --DECLARAÇÃO
   v_VAR NUMBER(10);
   --DECLARAÇÃO E ATRIBUIÇÃO
   v_ID NUMBER(5) := 1;
BEGIN
    --COMANDO
    v_ID := 2;
    --COMANDO DE SAÍDA
   dbms_output.put_line(v_ID);
END;