--APRENDENDO A USAR O %TYPE
--AO DEFINIRMOS UMA VARIALEL FAZEMOS
--VARIAVEL NUMBER(10) := 190199; POR EXEMPLO
--SE ESSA FOR UMA VARIAVEL DE UM CAMPO NA TABELA
--ELA PODE SOFRER ALTERAÇÕES DO DBA POR EXEMPLO
--AI QUANDO FORMOS INSERIR DARA UM ERRO
--POR ISSO NA DECLARAÇÃO PODEMOS DIZER "ESSA VARIAVEL
--É DO MESMO TIPO QUE ESSE CAMPO DA TABELA TAL"
DECLARE
   v_ID SEGMERCADO.ID%type := 2;
   v_DESCRICAO SEGMERCADO.DESCRICAO%type := 'Atacado';
BEGIN
   INSERT INTO SEGMERCADO (ID, DESCRICAO) VALUES (v_ID, v_DESCRICAO);
   COMMIT;
END;