/*APAGANDO AS TABELAS E RECRIANDO PARA REVER E ZERAR PARA OS EXEMPLOS
DE CONSULTA UM POUCO MAIS ABAIXO*/
DROP TABLE TB_CLIENTES;
DROP TABLE TB_PRODUTOS;

CREATE TABLE TB_CLIENTES
(CPF VARCHAR(11),
NOME VARCHAR(100),
ENDERECO1 VARCHAR(150),
ENDERECO2 VARCHAR(150),
BAIRRO VARCHAR(50),
CIDADE VARCHAR(50),
ESTADO VARCHAR(2),
CEP VARCHAR(8),
IDADE INT,
SEXO VARCHAR(1),
LIMITE_CREDITO FLOAT,
VOLUME_COMPRA FLOAT,
PRIMEIRA_COMPRA NUMBER(1),
CAMPO_DEVE_SER_RETIRADO INT);

ALTER TABLE TB_CLIENTES ADD CONSTRAINT PK_TB_CLIENTES PRIMARY KEY (CPF);
ALTER TABLE TB_CLIENTES ADD DATA_NASCIMENTO DATE;
ALTER TABLE TB_CLIENTES DROP COLUMN CAMPO_DEVE_SER_RETIRADO;

CREATE TABLE TB_PRODUTOS
(PRODUTO VARCHAR (20) PRIMARY KEY,
NOME VARCHAR (150) ,
EMBALAGEM VARCHAR (50) ,
TAMANHO VARCHAR (50) ,
SABOR VARCHAR (50) ,
PRECO_LISTA FLOAT);

ALTER TABLE TB_PRODUTOS DROP PRIMARY KEY;
ALTER TABLE TB_PRODUTOS ADD CONSTRAINT PK_TB_PRODUTOS 
PRIMARY KEY (PRODUTO);

/*INSERINDO DADOS PARA CONSULTA*/
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('19290992743','Fernando Cavalcante','R. Dois de Fevereiro','','Ã?gua Santa','Rio de Janeiro','RJ','22000000',TO_DATE('2000-02-12','YYYY-MM-DD'),18,'M',100000,200000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('2600586709','CÃ©sar Teixeira','Rua Conde de Bonfim','','Tijuca','Rio de Janeiro','RJ','22020001',TO_DATE('2000-03-12','YYYY-MM-DD'),18,'M',120000,220000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('95939180787','FÃ¡bio Carvalho','R. dos JacarandÃ¡s da PenÃ­nsula','','Barra da Tijuca','Rio de Janeiro','RJ','22002020',TO_DATE('1992-01-05','YYYY-MM-DD'),16,'M',90000,180000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('9283760794','Edson Meilelles','R. Pinto de Azevedo','','Cidade Nova','Rio de Janeiro','RJ','22002002',TO_DATE('1995-10-07','YYYY-MM-DD'),22,'M',150000,250000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('7771579779','Marcelo Mattos','R. Eduardo LuÃ­s Lopes','','BrÃ¡s','SÃ£o Paulo','SP','88202912',TO_DATE('1992-03-25','YYYY-MM-DD'),25,'M',120000,200000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5576228758','Petra Oliveira','R. BenÃ­cio de Abreu','','Lapa','SÃ£o Paulo','SP','88192029',TO_DATE('1995-11-14','YYYY-MM-DD'),22,'F',70000,160000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('8502682733','Valdeci da Silva','R. Srg. Ã‰dison de Oliveira','','Jardins','SÃ£o Paulo','SP','82122020',TO_DATE('1995-10-07','YYYY-MM-DD'),22,'M',110000,190000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('1471156710','Ã‰rica Carvalho','R. Iriquitia','','Jardins','SÃ£o Paulo','SP','80012212',TO_DATE('1990-09-01','YYYY-MM-DD'),27,'F',170000,245000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('3623344710','Marcos Nougeuira','Av. Pastor Martin Luther King Junior','','Inhauma','Rio de Janeiro','RJ','22002012',TO_DATE('1995-01-13','YYYY-MM-DD'),23,'M',110000,220000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('50534475787','Abel Silva ','Rua HumaitÃ¡','','HumaitÃ¡','Rio de Janeiro','RJ','22000212',TO_DATE('1995-09-11','YYYY-MM-DD'),22,'M',170000,260000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5840119709','Gabriel Araujo','R. Manuel de Oliveira','','Santo Amaro','SÃ£o Paulo','SP','80010221',TO_DATE('1985-03-16','YYYY-MM-DD'),32,'M',140000,210000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('94387575700','Walber Lontra','R. Cel. Almeida','','Piedade','Rio de Janeiro','RJ','22000201',TO_DATE('1989-06-20','YYYY-MM-DD'),28,'M',60000,120000,1);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('8719655770','Carlos Eduardo','Av. Gen. Guedes da Fontoura','','Jardins','SÃ£o Paulo','SP','81192002',TO_DATE('1983-12-20','YYYY-MM-DD'),34,'M',200000,240000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('5648641702','Paulo CÃ©sar Mattos','Rua HÃ©lio BeltrÃ£o','','Tijuca','Rio de Janeiro','RJ','21002020',TO_DATE('1991-08-30','YYYY-MM-DD'),26,'M',120000,220000,0);
INSERT INTO TB_CLIENTES (CPF,NOME,ENDERECO1,ENDERECO2,BAIRRO,CIDADE,ESTADO,CEP,DATA_NASCIMENTO,IDADE,SEXO,LIMITE_CREDITO,VOLUME_COMPRA,PRIMEIRA_COMPRA) VALUES ('492472718','Eduardo Jorge','R. Volta Grande','','Tijuca','Rio de Janeiro','RJ','22012002',TO_DATE('1994-07-19','YYYY-MM-DD'),23,'M',75000,95000,1);

INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1040107','Light - 350 ml - MelÃ¢ncia','Lata','350 ml','MelÃ¢ncia',4.555);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1037797','Clean - 2 Litros - Laranja','PET','2 Litros','Laranja',16.008);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1000889','Sabor da Montanha - 700 ml - Uva','Garrafa','700 ml','Uva',6.309);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1004327','Videira do Campo - 1,5 Litros - MelÃ¢ncia','PET','1,5 Litros','MelÃ¢ncia',19.51);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1088126','Linha Citros - 1 Litro - Limão','PET','1 Litro','Limão',7.004);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('544931','Frescor do VerÃ£o - 350 ml - Limão','Lata','350 ml','Limão',2.4595);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1078680','Frescor do VerÃ£o - 470 ml - Manga','Garrafa','470 ml','Manga',5.1795);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1042712','Linha Citros - 700 ml - Limão','Garrafa','700 ml','Limão',4.904);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('788975','PedaÃ§os de Frutas - 1,5 Litros - MaÃ§a','PET','1,5 Litros','MaÃ§a',18.011);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1002767','Videira do Campo - 700 ml - Cereja/MaÃ§a','Garrafa','700 ml','Cereja/MaÃ§a',8.41);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('231776','Festival de Sabores - 700 ml - AÃ§ai','Garrafa','700 ml','AÃ§ai',13.312);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('479745','Clean - 470 ml - Laranja','Garrafa','470 ml','Laranja',3.768);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1051518','Frescor do VerÃ£o - 470 ml - Limão','Garrafa','470 ml','Limão',3.2995);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1101035','Linha Refrescante - 1 Litro - Morango/Limão','PET','1 Litro','Morango/Limão',9.0105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('229900','PedaÃ§os de Frutas - 350 ml - MaÃ§a','Lata','350 ml','MaÃ§a',4.211);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1086543','Linha Refrescante - 1 Litro - Manga','PET','1 Litro','Manga',11.0105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('695594','Festival de Sabores - 1,5 Litros - AÃ§ai','PET','1,5 Litros','AÃ§ai',28.512);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('838819','Clean - 1,5 Litros - Laranja','PET','1,5 Litros','Laranja',12.008);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('326779','Linha Refrescante - 1,5 Litros - Manga','PET','1,5 Litros','Manga',16.5105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('520380','PedaÃ§os de Frutas - 1 Litro - MaÃ§a','PET','1 Litro','MaÃ§a',12.011);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1041119','Linha Citros - 700 ml - Lima/Limão','Garrafa','700 ml','Lima/Limão',4.904);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('243083','Festival de Sabores - 1,5 Litros - MaracujÃ¡','PET','1,5 Litros','MaracujÃ¡',10.512);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('394479','Sabor da Montanha - 700 ml - Cereja','Garrafa','700 ml','Cereja',8.409);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('746596','Light - 1,5 Litros - MelÃ¢ncia','PET','1,5 Litros','MelÃ¢ncia',19.505);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('773912','Clean - 1 Litro - Laranja','PET','1 Litro','Laranja',8.008);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('826490','Linha Refrescante - 700 ml - Morango/Limão','Garrafa','700 ml','Morango/Limão',6.3105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('723457','Festival de Sabores - 700 ml - MaracujÃ¡','Garrafa','700 ml','MaracujÃ¡',4.912);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('812829','Clean - 350 ml - Laranja','Lata','350 ml','Laranja',2.808);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('290478','Videira do Campo - 350 ml - MelÃ¢ncia','Lata','350 ml','MelÃ¢ncia',4.56);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('783663','Sabor da Montanha - 700 ml - Morango','Garrafa','700 ml','Morango',7.709);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('235653','Frescor do VerÃ£o - 350 ml - Manga','Lata','350 ml','Manga',3.8595);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1002334','Linha Citros - 1 Litro - Lima/Limão','PET','1 Litro','Lima/Limão',7.004);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1013793','Videira do Campo - 2 Litros - Cereja/MaÃ§a','PET','2 Litros','Cereja/MaÃ§a',24.01);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1096818','Linha Refrescante - 700 ml - Manga','Garrafa','700 ml','Manga',7.7105);
INSERT INTO TB_PRODUTOS (PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA) VALUES ('1022450','Festival de Sabores - 2 Litros - AÃ§ai','PET','2 Litros','AÃ§ai',38.012);
/*****************************************************************************/
/*FINALMENTE OS COMANDOS DE CONSULTA*/
/*****************************************************************************/
/*CONSULTA - TAIS CAMPOS - DA TABELA TAL*/
/* O * SIGNIFICA QUE EU QUERO TODOS OS CAMPOS*/
SELECT * FROM TB_CLIENTES;
SELECT * FROM TB_PRODUTOS;

/*PORÉM PODEMOS ESPECIFICAR QUAIS CAMPOS QUEREMOS*/
SELECT CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE,
SEXO, LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO
FROM TB_CLIENTES;

SELECT CPF, NOME, IDADE, DATA_NASCIMENTO
FROM TB_CLIENTES;

/*E NÓS QUE DECIDIMOS A ORDEM*/
SELECT IDADE, CPF, NOME, DATA_NASCIMENTO
FROM TB_CLIENTES;

/*PODEMOS TAMBÉM DAR UM NOME A CERTO CAMPO*/
SELECT CPF AS CPF_DO_CLIENTE, NOME AS NOME_DO_CLIENTE, IDADE, DATA_NASCIMENTO
FROM TB_CLIENTES;

/*PODEMOS COLOCAR FILTROS NA CONSULTA*/
/*CONSULTE TODOS OS CAMPOS QUANDO PRODUTOFOR IGUAL A 1037797*/
SELECT * FROM TB_PRODUTOS WHERE PRODUTO = '1037797';
/*ESTA ÚLTIMA CONSULTA FOI FEITA POR UMA CHAVE PRIMARIA,
MAS ISTO NÃO É UMA OBRIGAÇÃO, PODEMOS FILTRAR COM QUAL CAMPO QUISERMOS
EX: MOSTRE TODOS OS CLIENTES DO RIO DE JANEIRO*/
SELECT * FROM TB_CLIENTES WHERE CIDADE = 'Rio de Janeiro';

--O NOT INVERTE O VALOR, OU SEJA, SABOU = LARANJA VERDADEIRO O NOT
--INVERTE PARA FALSO - NESTE CASO IREMOS MOSTRAR TODOS QUE NÃO SEJAM
--SABOR LARANJA
SELECT * FROM TB_PRODUTOS WHERE NOT (SABOR = 'Laranja');

--O IN FUINCIONA COMO - SE O SABOR FOR UMA DESSAS OPÇÕES EU MOSTRO
SELECT * FROM TB_PRODUTOS WHERE SABOR IN ('Limão', 'Laranja');

/*SABENDO AGORA QUE PODEMOS FAZER FILTRO COM QUALQUER CONDIÇÃO
PODEMOS TB UTILIZAR ISSO EM OUTROS CASOS COMO O UPDATE
ANTES ESTAVAMOS ALTERANDO UM POR UM PELA CHAVE PRIMARIA
COMO UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE PRODUTO = '1088126';
MAS AGORA PODEMOS ALTERAR UM GRUPO DIRETO EX:*/
UPDATE TB_PRODUTOS SET SABOR = 'Cítricos' WHERE SABOR = 'Limão';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Cítricos';

SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limão';

/*EXISTEM TAMBÉM FILTROS CONDICIONAIS COMO:*/
SELECT * FROM TB_CLIENTES WHERE IDADE = 22;
SELECT * FROM TB_CLIENTES WHERE IDADE > 22;
SELECT * FROM TB_CLIENTES WHERE IDADE < 22;
SELECT * FROM TB_CLIENTES WHERE IDADE <= 22;
SELECT * FROM TB_CLIENTES WHERE IDADE >= 22;
SELECT * FROM TB_CLIENTES WHERE IDADE <> 22;/*DIFERENTE DE*/
/*É POSSÍVEL USAR CONDIÇÕES COM O VARCHAR TB
O DIFERENTE PODE SER LEGAL QUANDO QUEREMOS EXCLUIR UM CLIENTE DA CONSULTA
O IGUAL QUANDO QUEREMOS SABER DE UM CLIENTE ESPECÍFICO
PORÉM TOMAR CUIDADO COM O > E <
QUANDO COLOCAMOS ESSAS COMPARAÇÕES EM VARCAHR (EXEMPLO FERNANDO) ELE VAI VER
COMEÇA COM F TUDO QUE, POR EXMPLO, FOR MAIOR QUE F EU MOSTRO 
"UMA FALSA ORDEM ALFABÉTICA" - FALSA PQ ESTAMOS FALANDO DE CARACTERES DO UNICODE
ENTÃO O Á É MAIOR QUE O F POR EXEMPLO ENTÃO CUIDADO*/

SELECT * FROM TB_CLIENTES WHERE NOME <> 'Fernando Cavalcante';
SELECT * FROM TB_CLIENTES WHERE NOME >= 'Fernando Cavalcante';

/*PARA NUMEROS DECIMAIS*/
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16.008;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA = 16.008;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA <> 16.008;

/*CONSULTA DE DATAS*/
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = '07/10/95';
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO = TO_DATE('07/10/1995','DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO > TO_DATE('07/10/1995','DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE DATA_NASCIMENTO < TO_DATE('07/10/1995','DD/MM/YYYY');
SELECT * FROM TB_CLIENTES WHERE TO_CHAR(DATA_NASCIMENTO,'MM') = 9;

/*FILTROS COMPOSTOS*/
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA >= 16 AND PRECO_LISTA <= 21;
SELECT * FROM TB_CLIENTES WHERE IDADE > 22 AND SEXO = 'F';
SELECT * FROM TB_CLIENTES WHERE CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins';
SELECT * FROM TB_CLIENTES WHERE (IDADE > 22 AND SEXO = 'F') AND (CIDADE = 'Rio de Janeiro' OR BAIRRO = 'Jardins');