/*COMANDO DE INSEÇÃO*/
INSERT INTO TB_PRODUTOS
(PRODUTO, NOME, EMBALAGEM, TAMANHO, SABOR, PRECO_LISTA)
VALUES
('1040107','Light - 350 ml - Melância', 'Lata',
'350 ml','Melância',4.56);
/*INSERÇÃO DE DOIS ATRIBUTOS*/
INSERT INTO TB_PRODUTOS (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('544931', 'Frescor do Verão - 350 ml - Limão', 'PET', '350 ml','Limão',3.20);

INSERT INTO TB_PRODUTOS (
PRODUTO,  NOME, EMBALAGEM, TAMANHO, SABOR,
PRECO_LISTA) VALUES
('1078680', 'Frescor do Verão - 470 ml - Manga', 'Lata', '470 ml','Manga',5.18);

/*VISUALIZAR TUDO DE TAL TABELA*/
SELECT * FROM TB_PRODUTOS;

/*ATUALIZAR - TAL TABELA - TAIS CAMPOS - CONDIÇÃO PARA ACONTECER*/
UPDATE TB_PRODUTOS SET EMBALAGEM = 'Lata',
PRECO_LISTA = 2.46 
WHERE PRODUTO = '544931';

UPDATE TB_PRODUTOS SET EMBALAGEM = 'Garrafa'
WHERE PRODUTO = '1078680';

/*VISUALIZAR TUDO DE TAL TABELA*/
SELECT * FROM TB_PRODUTOS;