/*INSERÇÃO COM DATA*/
INSERT INTO TB_CLIENTES (CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO,
LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES
('00388934505','João da Silva','Rua Projetada A número 10',NULL , 'VILA ROMAN', 'TRÊS RIOS', 'RJ', '22222222',
53, 'M', 20000.00, 2000, 0,'12/10/1965'); 

SELECT * FROM TB_CLIENTES;

/*MOSTRANDO QUAIS SÃO OS MESES DO CAMPO DATA_NASCIMENTO
SERÃO OS MESMOS DO SISTEMA OPERACIONAL NESTE CASO*/
SELECT TO_CHAR(DATA_NASCIMENTO,'MM') FROM TB_CLIENTES;

DELETE FROM TB_CLIENTES WHERE CPF = '00388934505';

/*PARA GARANTIR QUE TIPO DE DATA ESTAMOS FALANDO PODEMOS FAZER ASSIM:*/
INSERT INTO TB_CLIENTES (CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO,
LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES
('00388934505','João da Silva','Rua Projetada A número 10',NULL , 'VILA ROMAN', 'TRÊS RIOS', 'RJ', '22222222',
53, 'M', 20000.00, 2000, 0,TO_DATE('12/10/1965','DD/MM/YYYY')); 

INSERT INTO TB_CLIENTES (CPF, NOME, ENDERECO1, ENDERECO2, BAIRRO, CIDADE, ESTADO, CEP, IDADE, SEXO,
LIMITE_CREDITO, VOLUME_COMPRA, PRIMEIRA_COMPRA, DATA_NASCIMENTO)
VALUES
('00388934777','João da Silva','Rua Projetada A número 10',NULL , 'VILA ROMAN', 'TRÊS RIOS', 'RJ', '22222222',
53, 'M', 20000.00, 2000, 0,TO_DATE('12/10/1965','MM/DD/YYYY'));

SELECT TO_CHAR(DATA_NASCIMENTO,'MM') FROM TB_CLIENTES;

DELETE FROM TB_CLIENTES WHERE CPF = '00388934777';

SELECT * FROM TB_CLIENTES;

--FUNÇÕES PARA DATAS
--FROM DUAL SIGNIFICA QUE É DE UMA TABELA NULA = SÓ FAZ OQ EU PEDI
--DIA DO SISTEMA OPERACIONAL
SELECT SYSDATE FROM DUAL;
--MASCARA PARA MOSTRAR DATA
SELECT TO_CHAR(SYSDATE, 'YYYY/MM/DD HH:MM:SS') FROM DUAL;
--SOMANDO DIAS
SELECT SYSDATE + 10 FROM DUAL;
--SUBTRAINDO DIAS
SELECT SYSDATE - 10 FROM DUAL;
--QUANTIDADE DE MESES ENTRE
SELECT MONTHS_BETWEEN(SYSDATE, TO_DATE('2019-01-01','YYYY-MM-DD')) FROM DUAL;
--ADICIONANDO MESES
SELECT ADD_MONTHS(SYSDATE, 10) FROM DUAL;
--PRÓXIMO DIA
SELECT NEXT_DAY(SYSDATE, 'SEXTA') FROM DUAL;
--ULTIMO DIA
SELECT LAST_DAY(SYSDATE) FROM DUAL;
--PRIMEIRO DIA DO ANO
SELECT TRUNC(SYSDATE, 'YEAR') FROM DUAL;
--PRIMEIRO DIA DO MES
SELECT TRUNC(SYSDATE, 'MONTH') FROM DUAL;
--PARA DATETIME ELE RETIRA AS HORAS
SELECT TRUNC(SYSDATE) FROM DUAL;


--ARREDONDA-> MAIS PERTO DO FIM DO ANO MOSTRA 1 DIA DO
--ANO QUE VEM, CASO CONTRARIO PRIMEIRO DIA DESSE ANO
SELECT ROUND(SYSDATE, 'YEAR') FROM DUAL;
